name: run time survey00

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * #UTC 00:00

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run main.py
        run: |
          python main.py

      - name: Overhead time survey
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
          git add . 
          git commit -m "Run"
          git pull
          git push origin main
